! FADJAR FATHURRAHMAN (20910015), MAY 2011

!------------------------------------------
SUBROUTINE FFT(DATAIN,DIM1,DIM2,DIM3,T_INV)
!------------------------------------------
  IMPLICIT NONE
  INCLUDE 'fftw3.f'
  ! ARGUMENTS
  INTEGER :: DIM1, DIM2, DIM3
  COMPLEX(8) :: DATAIN(DIM1,DIM2,DIM3)
  LOGICAL :: T_INV
  INTEGER(4) :: PLAN_BACKWARD
  INTEGER(4) :: PLAN_FORWARD
 
  IF(T_INV) THEN ! BACKWARD TRANSFORM
    CALL DFFTW_PLAN_DFT_3D(PLAN_BACKWARD,DIM3,DIM2,DIM1,DATAIN, &
          DATAIN,FFTW_BACKWARD,FFTW_ESTIMATE)
    CALL DFFTW_EXECUTE(PLAN_BACKWARD)
    CALL DFFTW_DESTROY_PLAN(PLAN_BACKWARD)
  ELSE ! FORWARD TRANSFORM
    CALL DFFTW_PLAN_DFT_3D(PLAN_FORWARD,DIM3,DIM2,DIM1,DATAIN, &
          DATAIN,FFTW_FORWARD,FFTW_ESTIMATE)
    CALL DFFTW_EXECUTE(PLAN_FORWARD)
    ! SCALE THE RESULT
    DATAIN=DATAIN/(DIM1*DIM2*DIM3) !TODO: USE BLAS INSTEAD
    CALL DFFTW_DESTROY_PLAN(PLAN_FORWARD)
  ENDIF
END SUBROUTINE

!END MODULE FFTW3_MODULE
